const catchAsyncError = require("./catchAsyncError");

exports.isAuthenticatedUser =catchAsyncError